[package]
name = "lapce-app"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
flate2.workspace = true
tar.workspace = true
alacritty_terminal.workspace = true
clap.workspace = true
rayon.workspace = true
lapce-core.workspace = true
lapce-rpc.workspace = true
lapce-proxy.workspace = true
strum.workspace = true
strum_macros.workspace = true
serde.workspace = true
serde_json.workspace = true
once_cell.workspace = true
crossbeam-channel.workspace = true
parking_lot.workspace = true
indexmap.workspace = true
log.workspace = true
anyhow.workspace = true
thiserror.workspace = true
reqwest.workspace = true
directories.workspace = true
notify.workspace = true
toml_edit.workspace = true
im.workspace = true
itertools.workspace = true
interprocess.workspace = true
lapce-xi-rope.workspace = true
lsp-types.workspace = true
smallvec.workspace = true
include_dir.workspace = true
regex.workspace = true
Inflector = "0.11.4"
open = "3.0.2"
unicode-width = "0.1.10"
fuzzy-matcher = "0.3.7"
sled = "0.34.7"
bytemuck = "1.8.0"
tokio = { version = "1.21", features = ["full"] }
futures = "0.3.26"
floem = { git = "https://github.com/lapce/floem", rev = "5b1536bed7360d5a86fc3f4465c1551b1842f230" }
# floem = { path = "../../workspaces/floem" }
config = { version = "0.13.2", default-features = false, features = ["toml"] }
structdesc = { git = "https://github.com/lapce/structdesc" }

[target.'cfg(target_os="macos")'.dependencies]
fs_extra = "1.2.0"
dmg = "0.1.1"

[target.'cfg(target_os="windows")'.dependencies]
zip = { version = "0.6.3", default-features = false, features = ["deflate"] }

[features]
default = ["all-languages", "updater"]
portable = ["lapce-core/portable"]
updater = []

# To build lapce with only some of the supported languages, for example:
#
#   cargo build --no-default-features -p lapce-ui \
#     --features lang-rust,lang-toml,lang-markdown,lang-json
#
all-languages = [
    "lang-bash",
    "lang-c",
    "lang-clojure",
    "lang-cmake",
    "lang-cpp",
    "lang-csharp",
    "lang-css",
    "lang-d",
    "lang-dart",
    "lang-dockerfile",
    "lang-elixir",
    "lang-elm",
    "lang-erlang",
    "lang-glimmer",
    "lang-glsl",
    "lang-go",
    "lang-hare",
    "lang-haskell",
    "lang-haxe",
    "lang-hcl",
    "lang-html",
    "lang-java",
    "lang-javascript",
    "lang-json",
    "lang-julia",
    "lang-kotlin",
    "lang-latex",
    "lang-lua",
    "lang-markdown",
    "lang-nix",
    "lang-ocaml",
    "lang-php",
    "lang-prisma",
    "lang-protobuf",
    "lang-python",
    "lang-ql",
    "lang-r",
    "lang-ruby",
    "lang-rust",
    "lang-scheme",
    "lang-scss",
    "lang-sql",
    "lang-svelte",
    "lang-swift",
    "lang-toml",
    "lang-typescript",
    "lang-vue",
    "lang-wgsl",
    "lang-xml",
    "lang-yaml",
    "lang-zig",
]

lang-bash = ["lapce-core/lang-bash"]
lang-c = ["lapce-core/lang-c"]
lang-clojure = ["lapce-core/lang-clojure"]
lang-cmake = ["lapce-core/lang-cmake"]
lang-cpp = ["lapce-core/lang-cpp"]
lang-csharp = ["lapce-core/lang-csharp"]
lang-css = ["lapce-core/lang-css"]
lang-d = ["lapce-core/lang-d"]
lang-dart = ["lapce-core/lang-dart"]
lang-dockerfile = ["lapce-core/lang-dockerfile"]
lang-elixir = ["lapce-core/lang-elixir"]
lang-elm = ["lapce-core/lang-elm"]
lang-erlang = ["lapce-core/lang-erlang"]
lang-glimmer = ["lapce-core/lang-glimmer"]
lang-glsl = ["lapce-core/lang-glsl"]
lang-go = ["lapce-core/lang-go"]
lang-hare = ["lapce-core/lang-hare"]
lang-haskell = ["lapce-core/lang-haskell"]
lang-haxe = ["lapce-core/lang-haxe"]
lang-hcl = ["lapce-core/lang-hcl"]
lang-html = ["lapce-core/lang-html"]
lang-java = ["lapce-core/lang-java"]
lang-javascript = ["lapce-core/lang-javascript"]
lang-json = ["lapce-core/lang-json"]
lang-julia = ["lapce-core/lang-julia"]
lang-kotlin = ["lapce-core/lang-kotlin"]
lang-latex = ["lapce-core/lang-latex"]
lang-lua = ["lapce-core/lang-lua"]
lang-markdown = ["lapce-core/lang-markdown"]
lang-nix = ["lapce-core/lang-nix"]
lang-ocaml = ["lapce-core/lang-ocaml"]
lang-php = ["lapce-core/lang-php"]
lang-prisma = ["lapce-core/lang-prisma"]
lang-protobuf = ["lapce-core/lang-protobuf"]
lang-python = ["lapce-core/lang-python"]
lang-ql = ["lapce-core/lang-ql"]
lang-r = ["lapce-core/lang-r"]
lang-ruby = ["lapce-core/lang-ruby"]
lang-rust = ["lapce-core/lang-rust"]
lang-scheme = ["lapce-core/lang-scheme"]
lang-scss = ["lapce-core/lang-scss"]
lang-sql = ["lapce-core/lang-sql"]
lang-svelte = ["lapce-core/lang-svelte"]
lang-swift = ["lapce-core/lang-swift"]
lang-toml = ["lapce-core/lang-toml"]
lang-typescript = ["lapce-core/lang-typescript"]
lang-vue = ["lapce-core/lang-vue"]
lang-wgsl = ["lapce-core/lang-wgsl"]
lang-xml = ["lapce-core/lang-xml"]
lang-yaml = ["lapce-core/lang-yaml"]
lang-zig = ["lapce-core/lang-zig"]
