white = "#ABB2BF"
black = "#282C34"
grey = "#3E4451"
light_grey = "#2c313c"
blue = "#61AFEF"
red = "#E06C75"
yellow = "#e5c07b"
orange = "#D19A66"
green = "#98C379"
purple = "#C678DD"
cyan = "#56b6c2"
magenta = "#C678DD"

"lapce.active_tab" = "$black"
"lapce.inactive_tab" = "$grey"
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#000000"
"lapce.border" = "#000000"
"lapce.scroll_bar" = "$grey"

"terminal.cursor" = "$white"
"terminal.foreground" = "$white"
"terminal.background" = "$black"
"terminal.white" = "$white"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "#545862"

"editor.background" = "$black"
"editor.foreground" = "$white"
"editor.dim" = "#5C6370"
"editor.focus" = "#CCCCCC"
"editor.caret" = "#528bff"
"editor.selection" = "$grey"
"editor.current_line" = "$light_grey"

"source_control.added" = "#50a14f32"
"source_control.removed" = "#ff526632"
"source_control.modified" = "#0184bc32"

"palette.background" = "#21252B"
"palette.current" = "#2C313A"

"completion.background" = "#21252B"
"completion.current" = "#2C313A"

"panel.background" = "#21252B"
"panel.current" = "#2C313A"

"status.background" = "#21252B"

"style.comment" = "#5C6370"

"style.constant" = "$yellow"
"style.type" = "$yellow"
"style.number" = "$yellow"
"style.enum" = "$yellow"
"style.struct" = "$yellow"
"style.structure" = "$yellow"
"style.interface" = "$yellow"

"style.function" = "$blue"
"style.method" = "$blue"
"style.function.method" = "$blue"

"style.keyword" = "$purple"
"style.selfKeyword" = "$purple"

"style.field" = "$red"
"style.property" = "$red"
"style.enumMember" = "$red"
"style.enum-member" = "$red"
"style.variable.other.member" = "$red"

"style.string" = "$green"

"style.type.builtin" = "$cyan"
"style.builtinType" = "$cyan"
