# --------------------------------- General --------------------------------------------

[[keymaps]]
key = "ctrl+p"
command = "palette"

[[keymaps]]
key = "Ctrl+P"
command = "palette.command"

[[keymaps]]
key = "ctrl+e"
command = "toggle_code_lens"
mode = "i"

[[keymaps]]
key = "ctrl+,"
command = "open_settings"

[[keymaps]]
key = "ctrl+k ctrl+s"
command = "open_keyboard_shortcuts"

# --------------------------------- Basic editing ---------------------------------------

[[keymaps]]
key = "ctrl+z"
command = "undo"
mode = "i"

[[keymaps]]
key = "ctrl+Z"
command = "redo"
mode = "i"

[[keymaps]]
key = "ctrl+x"
command = "clipboard_cut"
mode = "i"

[[keymaps]]
key = "ctrl+c"
command = "clipboard_copy"
mode = "i"

[[keymaps]]
key = "ctrl+v"
command = "clipboard_paste"
mode = "i"

[[keymaps]]
key = "ctrl+right"
command = "word_forward"
mode = "i"

[[keymaps]]
key = "ctrl+left"
command = "word_backward"
mode = "i"

[[keymaps]]
key = "ctrl+backspace"
command = "delete_word_backward"
mode = "i"

[[keymaps]]
key = "ctrl+|"
command = "match_pairs"
mode = "i"

# ------------------------------------ Multi cursor -------------------------------------

[[keymaps]]
key = "alt+ctrl+up"
command = "insert_cursor_above"
mode = "i"

[[keymaps]]
key = "alt+ctrl+down"
command = "insert_cursor_below"
mode = "i"

[[keymaps]]
key = "ctrl+l"
command = "select_current_line"
mode = "i"

[[keymaps]]
key = "ctrl+L"
command = "select_all_current"
mode = "i"

[[keymaps]]
key = "ctrl+u"
command = "select_undo"
mode = "i"

[[keymaps]]
key = "ctrl+d"
command = "select_next_current"
mode = "i"

[[keymaps]]
key = "ctrl+k ctrl+d"
command = "select_skip_current"
mode = "i"

# ------------------------------------ File Management --------------------------------

[[keymaps]]
key = "ctrl+s"
command = "save"

# ----------------------------------- Editor Management -------------------------------

[[keymaps]]
key = "ctrl+w"
command = "split_close"
mode = "i"

[[keymaps]]
key = "ctrl+F4"
command = "split_close"

[[keymaps]]
key = "ctrl+\\"
command = "split_vertical"

# --------------------------------- Rich Lanaguage Editing ----------------------------

[[keymaps]]
key = "ctrl+space"
command = "get_completion"
mode = "i"

[[keymaps]]
key = "ctrl+i"
command = "get_completion"
mode = "i"

[[keymaps]]
key = "ctrl+."
command = "show_code_actions"

# --------------------------------- Display -------------------------------------------

[[keymaps]]
key = "ctrl+E"
command = "toggle_file_explorer"

[[keymaps]]
key = "ctrl+F"
command = "toggle_search"

[[keymaps]]
key = "ctrl+X"
command = "toggle_plugin"

[[keymaps]]
key = "ctrl+M"
command = "toggle_problem"

# ------------------------------------ Navigation -------------------------------------

[[keymaps]]
key = "ctrl+O"
command = "palette.symbol"

[[keymaps]]
key = "ctrl+g"
command = "palette.line"
