[theme]
name = "Lapce Light"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

[theme.base]
white = "#FAFAFA"
black = "#383A42"
grey = "#E5E5E6"
light_grey = "#F2F2F2"
blue = "#4078F2"
red = "#E45649"
yellow = "#C18401"
green = "#50A14F"
purple = "#A626A4"
cyan = "#0184BC"
magenta = "#A626A4"

[theme.syntax]
"comment" = "#A0A1A7"

"constant" = "$yellow"
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$yellow"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "$yellow"

"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"

"keyword" = "$purple"
"selfKeyword" = "$purple"

"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"
"variable.other.member" = "$red"

"string" = "$green"

"type.builtin" = "$cyan"
"builtinType" = "$cyan"
"escape" = "$cyan"
"embedded" = "$cyan"

[theme.ui]
"lapce.active_tab" = "$white"
"lapce.inactive_tab" = "$grey"
"lapce.error" = "#E51400"
"lapce.warn" = "#E9A700"
"lapce.dropdown_shadow" = "#B4B4B4"
"lapce.border" = "#B4B4B4"
"lapce.scroll_bar" = "#B4B4B4"

"terminal.cursor" = "$black"
"terminal.foreground" = "$black"
"terminal.background" = "$white"
"terminal.white" = "$white"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "#090A0B"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "#A0A1A7"

"editor.background" = "$white"
"editor.foreground" = "$black"
"editor.dim" = "#A0A1A7"
"editor.focus" = "#000000"
"editor.caret" = "#526FFF"
"editor.selection" = "$grey"
"editor.current_line" = "#F2F2F2"
"editor.link" = "$cyan"

"source_control.added" = "#50A14F32"
"source_control.removed" = "#FF526632"
"source_control.modified" = "#0184BC32"

"palette.background" = "#EAEAEB"
"palette.current" = "#DBDBDC"

"completion.background" = "#EAEAEB"
"completion.current" = "#DBDBDC"

"hover.background" = "#EAEAEB"

"activity.background" = "#EAEAEB"
"activity.current" = "$white"

"panel.background" = "#EAEAEB"
"panel.current" = "#DBDBDC"
"panel.hovered" = "#E4E4E6"

"status.background" = "#EAEAEB"
"status.modal.normal" = "$blue"
"status.modal.insert" = "$red"
"status.modal.visual" = "$yellow"
"status.modal.terminal" = "$purple"

"markdown.blockquote" = "#686868"
