white = "#fafafa"
black = "#383a42"
grey = "#E5E5E6"
light_grey = "#f2f2f2"
blue = "#4078f2"
red = "#e45649"
yellow = "#c18401"
green = "#50A14F"
purple = "#A626A4"
cyan = "#0184bc"
magenta = "#A626A4"

"lapce.active_tab" = "$white"
"lapce.inactive_tab" = "$grey"
"lapce.error" = "#e51400"
"lapce.warn" = "#e9a700"
"lapce.dropdown_shadow" = "#b4b4b4"
"lapce.border" = "#b4b4b4"

"terminal.cursor" = "$black"
"terminal.foreground" = "$black"
"terminal.background" = "$white"
"terminal.white" = "$white"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "#A0A1A7"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "#090A0B"

"editor.background" = "$white"
"editor.foreground" = "$black"
"editor.dim" = "#A0A1A7"
"editor.caret" = "#526FFF"
"editor.selection" = "$grey"
"editor.current_line" = "$light_grey"

"palette.background" = "#eaeaeb"
"palette.current" = "#dbdbdc"

"completion.background" = "#eaeaeb"
"completion.current" = "#dbdbdc"

"panel.background" = "#eaeaeb"
"panel.current" = "#dbdbdc"

"status.background" = "#eaeaeb"

"style.comment" = "#A0A1A7"

"style.constant" = "$yellow"
"style.type" = "$yellow"
"style.typeAlias" = "$yellow"
"style.number" = "$yellow"
"style.enum" = "$yellow"
"style.struct" = "$yellow"
"style.structure" = "$yellow"
"style.interface" = "$yellow"
"style.attribute" = "$yellow"

"style.function" = "$blue"
"style.method" = "$blue"
"style.function.method" = "$blue"

"style.keyword" = "$purple"
"style.selfKeyword" = "$purple"

"style.field" = "$red"
"style.property" = "$red"
"style.enumMember" = "$red"
"style.enum-member" = "$red"

"style.string" = "$green"

"style.type.builtin" = "$cyan"
"style.builtinType" = "$cyan"
