#:schema ../extra/schemas/settings.json

[core]
modal = false
color-theme = "Lapce Dark"
icon-theme = "Lapce Codicons"
custom-titlebar = true

[editor]
font-family = "Monospace"
font-size = 13
code-lens-font-size = 2
line-height = 1.5
smart-tab = true
tab-width = 4
show-tab = true
show-bread-crumbs = true
scroll-beyond-last-line = true
cursor-surrounding-lines = 1
wrap-style = "editor-width"
wrap-column = 80
wrap-width = 600                        # px
sticky-header = true
completion-show-documentation = true
show-signature = true
signature-label-code-block = true
auto-closing-matching-pairs = true
auto-surround = true
hover-delay = 300                       # ms
modal-mode-relative-line-numbers = true
format-on-save = false
highlight-matching-brackets = true
highlight-selection-occurrences = true
highlight-scope-lines = false
autosave-interval = 0
format-on-autosave = true
enable-inlay-hints = true
inlay-hint-font-family = ""
inlay-hint-font-size = 0
enable-error-lens = true
error-lens-end-of-line = true
error-lens-font-family = ""
error-lens-font-size = 0
error-lens-multiline = false
enable-completion-lens = false
enable-inline-completion = true
completion-lens-font-family = ""
completion-lens-font-size = 0
blink-interval = 500                    # ms
multicursor-case-sensitive = true
multicursor-whole-words = true
render-whitespace = "none"
show-indent-guide = true
atomic-soft-tabs = false
double-click = "single"
move-focus-while-search = true
diff-context-lines = 3
scroll-speed-modifier = 1

[terminal]
font-family = ""
font-size = 0
line-height = 0

[terminal.default-profile]
macos   = "default"
linux   = "default"
windows = "default"

[terminal.profiles]
default = {}

[ui]
font-family = ""
font-size = 13
icon-size = 0
header-height = 36
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
list-line-height = 25
tab-close-button = "Right"

[color-theme]
name = ""

[color-theme.base]
white = "#ABB2BF"
black = "#282C34"
grey = "#3E4451"
blue = "#61AFEF"
red = "#E06C75"
yellow = "#E5C07B"
orange = "#D19A66"
green = "#98C379"
purple = "#C678DD"
cyan = "#56B6C2"
magenta = "#C678DD"

[color-theme.syntax]
"comment" = "#5C6370"
"constant" = "$yellow"
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$yellow"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "$yellow"
"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"
"keyword" = "$purple"
"keyword.control" = "$purple"
"selfKeyword" = "$purple"
"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"
"variable.other.member" = "$red"
"string" = "$green"
"type.builtin" = "$cyan"
"builtinType" = "$cyan"
"escape" = "$cyan"
"embedded" = "$cyan"
"symbol" = "$yellow"

[color-theme.ui]
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#000000"
"lapce.border" = "#000000"
"lapce.scroll_bar" = "#3E4451BB"

"lapce.button.primary.background" = "#50a14f"
"lapce.button.primary.foreground" = "$black"

# tab
"lapce.tab.active.background" = "$black"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "#528BFF"

"lapce.tab.inactive.background" = "#21252b"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "#528BFF77"

"lapce.tab.separator" = "#000000"

"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "#5C6370"

"lapce.remote.icon" = "$black"
"lapce.remote.local" = "#4078F2"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"

"lapce.plugin.name" = "#DDDDDD"
"lapce.plugin.description" = "$white"
"lapce.plugin.author" = "#B0B0B0"

"editor.background" = "$black"
"editor.foreground" = "$white"
"editor.dim" = "#5C6370"
"editor.focus" = "#CCCCCC"
"editor.caret" = "#528bFF"
"editor.selection" = "$grey"
"editor.current_line" = "#2C313C"
"editor.link" = "$blue"
"editor.visible_whitespace" = "#5C6370"
"editor.indent_guide" = "$grey"
"editor.drag_drop_background" = "#79c1fc55"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.sticky_header_background" = "$black"

"inlay_hint.foreground" = "$white"
"inlay_hint.background" = "#528bFF88"

"error_lens.error.foreground" = "$red"
"error_lens.error.background" = "#E06C7520"
"error_lens.warning.foreground" = "$yellow"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.other.foreground" = "#5C6370"
"error_lens.other.background" = "#5C637020"

"completion_lens.foreground" = "#5C6370"

"source_control.added" = "#50A14FCC"
"source_control.removed" = "#FF5266CC"
"source_control.modified" = "#0184BCCC"

"palette.background" = "#21252B"
"palette.foreground" = "$white"
"palette.current.background" = "#2C313A"
"palette.current.foreground" = "$white"

"completion.background" = "#21252B"
"completion.current" = "#2C313A"

"hover.background" = "#21252B"

"activity.background" = "#21252B"
"activity.current" = "$black"

"debug.breakpoint" = "$red"
"debug.breakpoint.hover" = "#E06C7566"

"panel.background" = "#21252B"
"panel.foreground" = "$white"
"panel.foreground.dim" = "#5C6370"
"panel.current.background" = "#2C313A"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#5C6370"
"panel.hovered.background" = "#343A45"
"panel.hovered.active.background" = "#5C6370"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#5C6370"

"status.background" = "#21252B"
"status.foreground" = "$white"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"

"markdown.blockquote" = "#898989"

"terminal.cursor" = "$white"
"terminal.foreground" = "$white"
"terminal.background" = "$black"
"terminal.white" = "$white"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "#545862"

[icon-theme]
name = ""

[icon-theme.ui]
"logo" = "lapce_logo.svg"
"menu" = "menu.svg"
"link" = "link.svg"
"error" = "error.svg"
"add" = "add.svg"
"close" = "close.svg"
"remote" = "remote.svg"
"unsaved" = "circle-filled.svg"
"warning" = "warning.svg"
"problem" = "problem.svg"
"debug" = "debug.svg"
"debug_breakpoint" = "circle-filled.svg"
"debug_alt" = "debug-alt.svg"
"debug_small" = "debug-alt-small.svg"
"debug_restart" = "debug-restart.svg"
"debug_continue" = "debug-continue.svg"
"debug_step_over" = "debug-step-over.svg"
"debug_step_into" = "debug-step-into.svg"
"debug_step_out" = "debug-step-out.svg"
"debug_pause" = "debug-pause.svg"
"debug_stop" = "debug-stop.svg"
"debug_console" = "debug-console.svg"
"debug_disconnect" = "debug-disconnect.svg"
"start" = "debug-start.svg"
"run_errors" = "run-errors.svg"
"settings" = "settings-gear.svg"
"terminal" = "terminal.svg"
"lightbulb" = "lightbulb.svg"
"extensions" = "extensions.svg"
"keyboard" = "keyboard.svg"
"breadcrumb_separator" = "chevron-right.svg"
"symbol_color" = "symbol-color.svg"

"window.close" = "chrome-close.svg"
"window.restore" = "chrome-restore.svg"
"window.maximize" = "chrome-maximize.svg"
"window.minimize" = "chrome-minimize.svg"

"file" = "file.svg"
"file_explorer" = "files.svg"
"file_picker_up" = "arrow-up.svg"

"image_loading" = "refresh.svg"
"image_error" = "error.svg"

"scm.icon" = "source-control.svg"
"scm.diff.modified" = "diff-modified.svg"
"scm.diff.added" = "diff-added.svg"
"scm.diff.removed" = "diff-removed.svg"
"scm.diff.renamed" = "diff-renamed.svg"
"scm.change.add" = "add.svg"
"scm.change.remove" = "remove.svg"

"palette.menu" = "chevron-down.svg"

"fold" = "fold.svg"
"fold.up" = "fold-up.svg"
"fold.down" = "fold-down.svg"

"dropdown.arrow" = "chevron-down.svg"

"location.forward" = "arrow-right.svg"
"location.backward" = "arrow-left.svg"

"item.opened" = "chevron-down.svg"
"item.closed" = "chevron-right.svg"

"directory.closed" = "folder.svg"
"directory.opened" = "folder-opened.svg"

"panel.restore" = "chevron-down.svg"
"panel.maximise" = "chevron-right.svg"

"split.horizontal" = "split-horizontal.svg"

"tab.previous" = "chevron-left.svg"
"tab.next" = "chevron-right.svg"

"sidebar.left.on" = "layout-sidebar-left.svg"
"sidebar.left.off" = "layout-sidebar-left-off.svg"
"sidebar.right.on" = "layout-sidebar-right.svg"
"sidebar.right.off" = "layout-sidebar-right-off.svg"

"layout.panel.on" = "layout-panel.svg"
"layout.panel.off" = "layout-panel-off.svg"

"search.icon" = "search.svg"
"search.clear" = "close.svg"
"search.forward" = "arrow-down.svg"
"search.backward" = "arrow-up.svg"
"search.case_sensitive" = "case-sensitive.svg"
"search.whole_word" = "whole-word.svg"
"search.regex" = "regex.svg"
"search.replace" = "replace.svg"
"search.replace_all" = "replace-all.svg"

"symbol_kind.array" = "symbol-array.svg"
"symbol_kind.boolean" = "symbol-boolean.svg"
"symbol_kind.class" = "symbol-class.svg"
"symbol_kind.constant" = "symbol-constant.svg"
"symbol_kind.enum_member" = "symbol-enum-member.svg"
"symbol_kind.enum" = "symbol-enum.svg"
"symbol_kind.event" = "symbol-event.svg"
"symbol_kind.field" = "symbol-field.svg"
"symbol_kind.file" = "symbol-file.svg"
"symbol_kind.function" = "symbol-method.svg"
"symbol_kind.interface" = "symbol-interface.svg"
"symbol_kind.key" = "symbol-key.svg"
"symbol_kind.method" = "symbol-method.svg"
"symbol_kind.namespace" = "symbol-namespace.svg"
"symbol_kind.number" = "symbol-numeric.svg"
"symbol_kind.object" = "symbol-namespace.svg"
"symbol_kind.operator" = "symbol-operator.svg"
"symbol_kind.property" = "symbol-property.svg"
"symbol_kind.string" = "symbol-string.svg"
"symbol_kind.struct" = "symbol-structure.svg"
"symbol_kind.type_parameter" = "symbol-parameter.svg"
"symbol_kind.variable" = "symbol-variable.svg"

"completion_item_kind.class" = "symbol-class.svg"
"completion_item_kind.constant" = "symbol-constant.svg"
"completion_item_kind.enum_member" = "symbol-enum-member.svg"
"completion_item_kind.enum" = "symbol-enum.svg"
"completion_item_kind.field" = "symbol-field.svg"
"completion_item_kind.function" = "symbol-method.svg"
"completion_item_kind.interface" = "symbol-interface.svg"
"completion_item_kind.keyword" = "symbol-keyword.svg"
"completion_item_kind.method" = "symbol-method.svg"
"completion_item_kind.module" = "symbol-namespace.svg"
"completion_item_kind.property" = "symbol-property.svg"
"completion_item_kind.snippet" = "symbol-snippet.svg"
"completion_item_kind.string" = "symbol-string.svg"
"completion_item_kind.struct" = "symbol-structure.svg"
"completion_item_kind.variable" = "symbol-variable.svg"

[icon-theme.foldername]

[icon-theme.filename]

[icon-theme.extension]
