[lapce]
modal = false
color-theme = "Lapce Dark"
icon-theme = ""
terminal-shell = ""

[plugins]
auto-check = true

[editor]
font-family = "Cascadia Code"
font-size = 13
code-lens-font-size = 2
line-height = 25
tab-width = 4
show-tab = true
hover-delay = 300 # ms
