[lapce]
modal = false
color-theme = "Lapce Dark"
icon-theme = ""
custom-titlebar = true

[editor]
font-family = "Cascadia Code"
font-size = 13
code-lens-font-size = 2
line-height = 1.35
tab-width = 4
show-tab = true
show-bread-crumbs = true
scroll-beyond-last-line = true
sticky-header = true
completion-show-documentation = true
hover-delay = 300             # ms
modal-mode-relative-line-numbers = true
format-on-save = true
enable-inlay-hints = true
inlay-hint-font-family = ""
inlay-hint-font-size = 0
enable-error-lens = true
error-lens-end-of-line = true
error-lens-font-family = ""
error-lens-font-size = 0
blink-interval = 500 # ms
multicursor-case-sensitive = true
multicursor-whole-words = true
render-whitespace = "none"

[terminal]
font-family = ""
font-size = 0
line-height = 0
shell = ""

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0

[theme]
name = ""

[theme.base]
white = "#ABB2BF"
black = "#282C34"
grey = "#3E4451"
blue = "#61AFEF"
red = "#E06C75"
yellow = "#E5C07B"
orange = "#D19A66"
green = "#98C379"
purple = "#C678DD"
cyan = "#56B6C2"
magenta = "#C678DD"

[theme.syntax]
"comment" = "#5C6370"
"constant" = "$yellow"
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$yellow"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "$yellow"
"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"
"keyword" = "$purple"
"selfKeyword" = "$purple"
"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"
"variable.other.member" = "$red"
"string" = "$green"
"type.builtin" = "$cyan"
"builtinType" = "$cyan"
"escape" = "$cyan"
"embedded" = "$cyan"
"symbol" = "$yellow"

[theme.ui]
"lapce.active_tab" = "$black"
"lapce.inactive_tab" = "$grey"
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#000000"
"lapce.border" = "#000000"
"lapce.scroll_bar" = "$grey"

"editor.background" = "$black"
"editor.foreground" = "$white"
"editor.dim" = "#5C6370"
"editor.focus" = "#CCCCCC"
"editor.caret" = "#528bFF"
"editor.selection" = "$grey"
"editor.current_line" = "#2C313C"
"editor.link" = "$cyan"

"inlay_hint.foreground" = "$white"
"inlay_hint.background" = "#528bFF88"

"error_lens.error.foreground" = "$red"
"error_lens.error.background" = "#E06C7520"
"error_lens.warning.foreground" = "$yellow"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.other.foreground" = "#5C6370"
"error_lens.other.background" = "#5C637020"

"source_control.added" = "#50A14F32"
"source_control.removed" = "#FF526632"
"source_control.modified" = "#0184BC32"

"palette.background" = "#21252B"
"palette.current" = "#2C313A"

"completion.background" = "#21252B"
"completion.current" = "#2C313A"

"hover.background" = "#21252B"

"activity.background" = "#21252B"
"activity.current" = "$black"

"panel.background" = "#21252B"
"panel.current" = "#2C313A"
"panel.hovered" = "#343A45"

"status.background" = "#21252B"
"status.modal.normal" = "$blue"
"status.modal.insert" = "$red"
"status.modal.visual" = "$yellow"
"status.modal.terminal" = "$purple"

"markdown.blockquote" = "#898989"

"terminal.cursor" = "$white"
"terminal.foreground" = "$white"
"terminal.background" = "$black"
"terminal.white" = "$white"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "#545862"
