[lapce]
modal = false
color-theme = "Lapce Dark"
icon-theme = ""
terminal-shell = ""

[editor]
font-family = "Cascadia Code"
font-size = 13
code-lens-font-size = 2
line-height = 25
tab-width = 4
show-tab = true
