[lapce]
modal = false
color-theme = "Lapce Dark"
icon-theme = ""

[ui]
font-family = ""
font-size = 13
header-height = 30
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow = true

[editor]
font-family = "Cascadia Code"
font-size = 13
code-lens-font-size = 2
line-height = 25
tab-width = 4
show-tab = true
hover-delay = 300 # ms

[terminal]
font-family = ""
font-size = 0
line-height = 0
shell = ""
